import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";
import {
  filterFindingsToAiLineRanges,
  filterScanFiles,
  isAiCommit,
  parseBlamePorcelain,
  type GitRunner
} from "../src/gitFilter";
import type { Finding } from "../src/types";

const aiHash = "a".repeat(40);
const humanHash = "b".repeat(40);

test("detects AI commits by author, message, and aggressive mode", () => {
  assert.equal(
    isAiCommit(
      {
        authorName: "github-actions[bot]",
        authorEmail: "41898282+github-actions[bot]@users.noreply.github.com",
        message: "regular commit"
      },
      "author"
    ),
    true
  );
  assert.equal(
    isAiCommit(
      {
        authorName: "Human",
        authorEmail: "human@example.com",
        message: "Generated by AI assistant"
      },
      "message"
    ),
    true
  );
  assert.equal(
    isAiCommit(
      {
        authorName: "Human",
        authorEmail: "human@example.com",
        message: "manual refactor"
      },
      "aggressive"
    ),
    false
  );
});

test("uses git blame to retain only AI-authored changed lines and findings", async () => {
  const cwd = process.cwd();
  const aiFile = path.join(cwd, "src", "mixed.ts");
  const humanFile = path.join(cwd, "src", "human.ts");
  const runner = fakeGitRunner({
    "diff --name-only --diff-filter=ACMRTUXB base...head": "src/mixed.ts\nsrc/human.ts\n",
    "diff --unified=0 base...head -- src/mixed.ts": "@@ -1,0 +1,2 @@\n+const ai = eval(input);\n+const human = safe(input);\n",
    "blame --line-porcelain -L 1,2 head -- src/mixed.ts": `${blameLine(aiHash, 1, "github-actions[bot]", "bot@example.com")}${blameLine(humanHash, 2, "Human", "human@example.com")}`,
    "diff --unified=0 base...head -- src/human.ts": "@@ -4,0 +4,1 @@\n+const human = safe(input);\n",
    "blame --line-porcelain -L 4,4 head -- src/human.ts": blameLine(humanHash, 4, "Human", "human@example.com")
  });

  const result = await filterScanFiles([aiFile, humanFile], {
    mode: "ai-code-scan",
    aiDetection: "author",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, [aiFile]);
  assert.deepEqual(result.aiLineRanges?.get(normalize(aiFile)), [{ startLine: 1, endLine: 1 }]);
  assert.deepEqual(
    filterFindingsToAiLineRanges([finding(1), finding(2), finding(3)], aiFile, result.aiLineRanges).map((item) => item.line),
    [1]
  );
});

test("uses the blamed commit message for line-level AI message attribution", async () => {
  const cwd = process.cwd();
  const file = path.join(cwd, "src", "message.ts");
  const runner = fakeGitRunner({
    "diff --name-only --diff-filter=ACMRTUXB base...head": "src/message.ts\n",
    "diff --unified=0 base...head -- src/message.ts": "@@ -8,0 +8,1 @@\n+const query = input;\n",
    "blame --line-porcelain -L 8,8 head -- src/message.ts": blameLine(humanHash, 8, "Human", "human@example.com"),
    [`show -s --format=%an%x00%ae%x00%B ${humanHash}`]: "Human\x00human@example.com\x00Co-authored-by: Copilot <bot@example.com>\n"
  });

  const result = await filterScanFiles([file], {
    mode: "ai-code-scan",
    aiDetection: "message",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, [file]);
  assert.deepEqual(result.aiLineRanges?.get(normalize(file)), [{ startLine: 8, endLine: 8 }]);
});

test("uses aggressive diff-size fallback for large added files without blame", async () => {
  const cwd = process.cwd();
  const file = path.join(cwd, "src", "large.ts");
  const runner = fakeGitRunner({
    "diff --name-only --diff-filter=ACMRTUXB base...head": "src/large.ts\n",
    "diff --unified=0 base...head -- src/large.ts": "@@ -0,0 +1,75 @@\n"
  });

  const result = await filterScanFiles([file], {
    mode: "ai-code-scan",
    aiDetection: "aggressive",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, [file]);
  assert.deepEqual(result.aiLineRanges?.get(normalize(file)), [{ startLine: 1, endLine: 75 }]);
});

test("falls back to full scan when git history cannot be inspected", async () => {
  const cwd = process.cwd();
  const files = [path.join(cwd, "src", "all.ts")];
  const runner: GitRunner = {
    async run(): Promise<string> {
      throw new Error("not a git repository");
    }
  };

  const result = await filterScanFiles(files, {
    mode: "ai-code-scan",
    aiDetection: "author",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, files);
  assert.equal(result.scannedMode, "full-scan");
  assert.match(result.warning ?? "", /falling back to full scan/);
});

test("parses blame records with boundary commits", () => {
  const records = parseBlamePorcelain(blameLine(`^${aiHash}`, 7, "Cursor Bot", "cursor@example.com"));
  assert.deepEqual(records, [
    {
      hash: aiHash,
      line: 7,
      authorName: "Cursor Bot",
      authorEmail: "cursor@example.com",
      message: ""
    }
  ]);
});

function blameLine(hash: string, line: number, authorName: string, authorEmail: string): string {
  return `${hash} ${line} ${line} 1\nauthor ${authorName}\nauthor-mail <${authorEmail}>\nauthor-time 0\nauthor-tz +0000\ncommitter ${authorName}\ncommitter-mail <${authorEmail}>\nsummary commit\nfilename file.ts\n\tline ${line}\n`;
}

function fakeGitRunner(responses: Record<string, string>): GitRunner {
  return {
    async run(args: string[]): Promise<string> {
      const key = args.join(" ");
      const response = responses[key];
      if (response === undefined) {
        throw new Error(`Unexpected git command: ${key}`);
      }
      return response;
    }
  };
}

function normalize(filePath: string): string {
  return path.resolve(filePath).replace(/\\/g, "/").toLowerCase();
}

function finding(line: number): Finding {
  return {
    id: `finding-${line}`,
    type: "ai_pattern_error",
    severity: "high",
    message: "Unsafe AI-generated code.",
    file: "mixed.ts",
    line,
    column: 1,
    evidence: "code",
    detection_layer: "L1",
    detection_rule: "ai_pattern_eval",
    timestamp: 1,
    dismissed: false
  };
}
