import assert from "node:assert/strict";
import path from "node:path";
import test from "node:test";
import { filterScanFiles, isAiCommit, type GitRunner } from "../src/gitFilter";

test("detects AI commits by author, message, and aggressive mode", () => {
  assert.equal(
    isAiCommit(
      {
        authorName: "github-actions[bot]",
        authorEmail: "41898282+github-actions[bot]@users.noreply.github.com",
        message: "regular commit"
      },
      "author"
    ),
    true
  );
  assert.equal(
    isAiCommit(
      {
        authorName: "Human",
        authorEmail: "human@example.com",
        message: "Generated by AI assistant"
      },
      "message"
    ),
    true
  );
  assert.equal(
    isAiCommit(
      {
        authorName: "Human",
        authorEmail: "human@example.com",
        message: "manual refactor"
      },
      "aggressive"
    ),
    false
  );
});

test("filters ai-code-scan files by changed files and AI authors", async () => {
  const cwd = process.cwd();
  const files = [path.join(cwd, "src", "ai.ts"), path.join(cwd, "src", "human.ts"), path.join(cwd, "src", "unchanged.ts")];
  const runner = fakeGitRunner({
    "diff --name-only --diff-filter=ACMRTUXB base...head": "src/ai.ts\nsrc/human.ts\n",
    "log --format=%an%x00%ae%x00%B%x1e base...head -- src/ai.ts": "github-actions[bot]\x00bot@example.com\x00generated code\x1e",
    "log --format=%an%x00%ae%x00%B%x1e base...head -- src/human.ts": "Human\x00human@example.com\x00manual change\x1e"
  });

  const result = await filterScanFiles(files, {
    mode: "ai-code-scan",
    aiDetection: "author",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, [path.join(cwd, "src", "ai.ts")]);
  assert.equal(result.scannedMode, "ai-code-scan");
  assert.equal(result.warning, undefined);
});

test("filters ai-code-scan files by commit message", async () => {
  const cwd = process.cwd();
  const files = [path.join(cwd, "src", "message.ts")];
  const runner = fakeGitRunner({
    "diff --name-only --diff-filter=ACMRTUXB base...head": "src/message.ts\n",
    "log --format=%an%x00%ae%x00%B%x1e base...head -- src/message.ts": "Human\x00human@example.com\x00Co-authored-by: Copilot <bot@example.com>\x1e"
  });

  const result = await filterScanFiles(files, {
    mode: "ai-code-scan",
    aiDetection: "message",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, [path.join(cwd, "src", "message.ts")]);
});

test("uses aggressive diff-size fallback for large added files", async () => {
  const cwd = process.cwd();
  const files = [path.join(cwd, "src", "large.ts")];
  const runner = fakeGitRunner({
    "diff --name-only --diff-filter=ACMRTUXB base...head": "src/large.ts\n",
    "log --format=%an%x00%ae%x00%B%x1e base...head -- src/large.ts": "Human\x00human@example.com\x00manual change\x1e",
    "diff --numstat base...head -- src/large.ts": "75\t0\tsrc/large.ts\n"
  });

  const result = await filterScanFiles(files, {
    mode: "ai-code-scan",
    aiDetection: "aggressive",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, [path.join(cwd, "src", "large.ts")]);
});

test("falls back to full scan when git history cannot be inspected", async () => {
  const cwd = process.cwd();
  const files = [path.join(cwd, "src", "all.ts")];
  const runner: GitRunner = {
    async run(): Promise<string> {
      throw new Error("not a git repository");
    }
  };

  const result = await filterScanFiles(files, {
    mode: "ai-code-scan",
    aiDetection: "author",
    baseRef: "base",
    headRef: "head",
    cwd,
    runner
  });

  assert.deepEqual(result.files, files);
  assert.equal(result.scannedMode, "full-scan");
  assert.match(result.warning ?? "", /falling back to full scan/);
});

function fakeGitRunner(responses: Record<string, string>): GitRunner {
  return {
    async run(args: string[]): Promise<string> {
      const key = args.join(" ");
      const response = responses[key];
      if (response === undefined) {
        throw new Error(`Unexpected git command: ${key}`);
      }
      return response;
    }
  };
}
